# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: accounts.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61\x63\x63ounts.proto\"3\n\x07\x41\x63\x63ount\x12\x12\n\naccount_id\x18\x01 \x01(\r\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x02 \x01(\t\",\n\x14\x43reateAccountRequest\x12\x14\n\x0c\x61\x63\x63ount_name\x18\x01 \x01(\t\"0\n\x13\x43reateAccountResult\x12\x19\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x08.Account\"/\n\x12GetAccountsRequest\x12\x19\n\x07\x61\x63\x63ount\x18\x01 \x03(\x0b\x32\x08.Account\".\n\x11GetAccountsResult\x12\x19\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x08.Account2\x82\x01\n\x08\x41\x63\x63ounts\x12<\n\rCreateAccount\x12\x15.CreateAccountRequest\x1a\x14.CreateAccountResult\x12\x38\n\x0bGetAccounts\x12\x13.GetAccountsRequest\x1a\x12.GetAccountsResult0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'accounts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACCOUNT']._serialized_start=18
  _globals['_ACCOUNT']._serialized_end=69
  _globals['_CREATEACCOUNTREQUEST']._serialized_start=71
  _globals['_CREATEACCOUNTREQUEST']._serialized_end=115
  _globals['_CREATEACCOUNTRESULT']._serialized_start=117
  _globals['_CREATEACCOUNTRESULT']._serialized_end=165
  _globals['_GETACCOUNTSREQUEST']._serialized_start=167
  _globals['_GETACCOUNTSREQUEST']._serialized_end=214
  _globals['_GETACCOUNTSRESULT']._serialized_start=216
  _globals['_GETACCOUNTSRESULT']._serialized_end=262
  _globals['_ACCOUNTS']._serialized_start=265
  _globals['_ACCOUNTS']._serialized_end=395
# @@protoc_insertion_point(module_scope)
